//LOGIN
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_REQUEST_SUCCESS = 'USER_LOGIN_REQUEST_SUCCESS';
export const USER_LOGIN_REQUEST_FAILURE = 'USER_LOGIN_REQUEST_FAILURE';

//LOG OUT
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_REQUEST_SUCCESS = 'USER_LOGOUT_REQUEST_SUCCESS';
export const USER_LOGOUT_REQUEST_FAILURE = 'USER_LOGOUT_REQUEST_FAILURE';

//UPDATE USER
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_REQUEST_SUCCESS = 'USER_UPDATE_REQUEST_SUCCESS';
export const USER_UPDATE_REQUEST_FAILURE = 'USER_UPDATE_REQUEST_FAILURE';

//CHECK LOGIN
export const USER_LOGIN_CHECK = 'USER_LOGIN_CHECK';
export const USER_LOGIN_CHECK_SUCCESS = 'USER_LOGIN_CHECK_SUCCESS';
export const USER_LOGIN_CHECK_FAILURE = 'USER_LOGIN_CHECK_FAILURE';

//Driver
export const DRIVER_USER_LIST = 'DRIVER_USER_LIST';
